spring:
  application:
    name: item-service    #当前项目的应用名
  rabbitmq:
    host: 192.168.64.5
    port: 5672
    username: admin
    password: admin
  
    
#server:
 # port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
---
spring:
  profiles: item1  #--spring.profiles.active=item1  sp02-itemservice-8001
  
server:
  port: 8001
---
spring:
  profiles: item2  #--spring.profiles.active=item2   sp02-itemservice-8002

server:
  port: 8002